### ISSUE TITLE
exclude note properties from merge

### ISSUE THREAD

**Issue by osaze-nosaze** [fnya/merge-notes#1]
**Problem description.**
The yaml/properties of merged notes are included in merges. This makes it difficult to produce clean documents for distribution to colleagues or long manuscripts to publishers, unless one manually deletes the yaml/properties.

**Desired solution**
I want to be able to merge the notes in a folder without their yaml/properties included in the resulting merged note.

**Suggestions considered**
You might include a toggle button in the plugin's options page that allows the user to select whether or not they want to include note yaml/properties in the merge always. You might also place that toggle in a dialogue box (I beg your pardon if that is the wrong term) that pops up whenever the user clicks the "merge folder" command, so that they can make that choice for each merge instance.

**Use case**
This feature would facilitate the merging of atomic notes into longform documents for distribution, the receiver of which usually does not require to see the yaml/properties of the component notes.

**Comment by fnya** [comment]
@osaze-nosaze 
Thanks for the great suggestions!

I have considered other uses and supported the yaml properties in a slightly different way.

The yaml properties will be grouped at the top after merging, so please remove the properties in the source code view.

This feature has been available since 0.0.7.

**Comment by osaze-nosaze** [comment]
Hi, thank you for the quick response. Indeed, I found on doing a new merge that the frontmatters of the merged notes are now consolidated at the top of the new note. Thank you for the solution. However, it will probably work best with merges involving only a few notes. What if one has to merge a larger number of notes? For example, I recently had to merge 165 component notes into one long manuscript. Per your solution, their consolidated frontmatters at the top of the manuscript resulting from their merge would run to tens of pages. Yes, one can remove them by selecting the pages and pressing "delete"; but is it perhaps possible to simply exclude the yaml/properties from the merge in the first place? Are there technical reasons why this might be impossible?

Also, is it possible to exclude the filenames of the component notes from the merge?

I appreciate your plugin and think these suggestion might enhance its utility for longform writers.

**Comment by fnya** [comment]
@osaze-nosaze 
I have incorporated your suggestion in version 0.0.8. Could you please give it a try?

**Comment by osaze-nosaze** [comment]
Hi, @fnya
Thank you so much for your work. I have tried your plugin again, and it is excellent with the improvements you have made. Great work!! I will surely follow your work as you develop the plugin further, and will certainly show my material appreciation later---for now, however, I can offer principally suggestions. Please keep up the good work.
