### ISSUE TITLE
Merged note is empty

### ISSUE THREAD

**Issue by electric-m** [fnya/merge-notes#2]
No matter what I do, every time I try to merge some notes, the resulting "merged" file is empty.
Any chance to help here?

Regards

**Comment by fnya** [comment]
@electric-m 
I have never had such a problem before, but it may happen when a Markdown file starts with `---` and ends with `---` and the exclude properties checkbox is checked.

**Comment by fnya** [comment]
Since I do not understand the details, this issue is closed.
